#!/bin/bash

# This literally just runs the python script, but it lets it be run via
# rosrun sumobot_xbox_controller node

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

python $SCRIPT_DIR/xbox_listener.py
