name: sumobot
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: It's my sumobot
description: It's ya boiiiii

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  workspace:
    plugin: catkin
    rosdistro: kinetic
    catkin-packages: [sumobot_motion_master, sumobot_drive, sumobot_xbox_controller, sumobot_msgs]
    build-packages:
      - python-pygame
    stage-packages:
      - python-pygame
      - python-numpy
      - python-opengl
      - libsdl-image1.2-dev
      - libsdl-mixer1.2-dev
      - libsdl-ttf2.0-dev
      - libsmpeg-dev
      - libsdl1.2-dev
      - libportmidi-dev
      - libswscale-dev
      - libavformat-dev
      - libavcodec-dev
      - libfreetype6-dev
      - xfonts-base
      - xfonts-100dpi
      - xfonts-75dpi
      - xfonts-cyrillic
      - fontconfig
      - fonts-freefont-ttf

apps:
  main:
    command: roslaunch sumobot_motion_master sumobot.launch
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    plugs: [network, network-bind]
    #daemon: simple
