name: sumobot
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: It's my sumobot
description: It's ya boiiiii

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts:
  workspace:
    plugin: catkin
    rosdistro: kinetic
    catkin-packages: [sumobot_motion_master, sumobot_drive, sumobot_xbox_controller]

apps:
  roscore:
    command: roscore
    plugs: [network, network-bind]
  xbox_listener:
    command: rosrun sumobot_xbox_controller node
    plugs: [network, network-bind]
  drive:
    command: rosrun sumobot_drive node
    plugs: [network, network-bind]
  master:
    command: rosrun sumobot_motion_master node
    plugs: [network, network-bind]
